const state = () => ({
    all: [
        {
            id: 1,
            name: 'Blusa Social',
            price: 191.00,
            offer: true,
            offerPrice: 3,
            latest: true,
            bestSellers: false,
            trending: false,
            image: require('../static/products/airmax-01.jpg'),
            imageHover: require('../static/products/airmax-02.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 2,
            name: 'Bermuda Jeans',
            price: 300.00,
            offer: false,
            offerPrice: 3,
            latest: true,
            bestSellers: false,
            trending: false,
            image: require('../static/products/airmax-01.jpg'),
            imageHover: require('../static/products/airmax-02.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 3,
            name: 'Camiseta Gucci',
            price: 166.00,
            offer: true,
            offerPrice: 5,
            latest: true,
            bestSellers: false,
            trending: false,
            image: require('../static/products/airmax-01.jpg'),
            imageHover: require('../static/products/airmax-02.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 4,
            name: 'Tenis Air Max - 500',
            price: 200.00,
            offer: false,
            offerPrice: 7,
            latest: true,
            bestSellers: false,
            trending: false,
            image: require('../static/products/airmax-01.jpg'),
            imageHover: require('../static/products/airmax-02.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 5,
            name: 'Tênis Air Jordan',
            price: 150.00,
            offer: true,
            offerPrice: 7,
            latest: true,
            bestSellers: false,
            trending: false,
            image: require('../static/products/airmax-01.jpg'),
            imageHover: require('../static/products/airmax-02.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 6,
            name: 'Calça Leg',
            price: 177.00,
            offer: false,
            offerPrice: 7,
            latest: true,
            bestSellers: false,
            trending: false,
            image: require('../static/products/airmax-01.jpg'),
            imageHover: require('../static/products/airmax-02.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 7,
            name: 'Colar Feminino',
            price: 300.00,
            offer: true,
            offerPrice: 4,
            latest: true,
            bestSellers: false,
            trending: false,
            image: require('../static/products/airmax-01.jpg'),
            imageHover: require('../static/products/airmax-02.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 8,
            name: 'Pulseira Key',
            price: 191.00,
            offer: false,
            offerPrice: 4,
            latest: true,
            bestSellers: false,
            trending: false,
            image: require('../static/products/airmax-01.jpg'),
            imageHover: require('../static/products/airmax-02.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 9,
            name: 'Cueca Calvin Klein',
            price: 150.00,
            offer: true,
            offerPrice: 7,
            latest: false,
            bestSellers: true,
            trending: false,
            image: require('../static/products/airmax-01.jpg'),
            imageHover: require('../static/products/airmax-02.jpg'),
            timePeriod: true,
            dateTime: new Date("August 19, 2022 17:00:00 PDT")
        },
        {
            id: 10,
            name: 'Loungerie Vermelha',
            price: 177.00,
            offer: false,
            offerPrice: 7,
            latest: false,
            bestSellers: true,
            trending: false,
            image: require('../static/products/airmax-01.jpg'),
            imageHover: require('../static/products/airmax-02.jpg'),
            timePeriod: false,
            trendingProducts: false,
            dateTime: new Date("August 19, 2021 17:00:00 PDT")
        },
        {
            id: 11,
            name: 'Relógio',
            price: 300.00,
            offer: true,
            offerPrice: 4,
            latest: false,
            bestSellers: true,
            trending: false,
            image: require('../static/products/airmax-01.jpg'),
            imageHover: require('../static/products/airmax-02.jpg'),
            timePeriod: true,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 12,
            name: 'Cinto Off-White',
            price: 191.00,
            offer: false,
            offerPrice: 4,
            latest: false,
            bestSellers: true,
            trending: false,
            image: require('../static/products/airmax-01.jpg'),
            imageHover: require('../static/products/airmax-02.jpg'),
            timePeriod: false,
            dateTime: new Date("April 19, 2020 17:00:00 PDT")
        },
        {
            id: 13,
            name: 'Par de Meias',
            price: 150.00,
            offer: true,
            offerPrice: 7,
            latest: false,
            bestSellers: false,
            trending: true,
            image: require('../static/products/airmax-01.jpg'),
            imageHover: require('../static/products/airmax-02.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 14,
            name: 'Conjunto de 10 Cuecas',
            price: 177.00,
            offer: false,
            offerPrice: 7,
            latest: false,
            bestSellers: false,
            trending: true,
            image: require('../static/products/airmax-01.jpg'),
            imageHover: require('../static/products/airmax-02.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 15,
            name: 'Biquini',
            price: 300.00,
            offer: true,
            offerPrice: 4,
            latest: false,
            bestSellers: false,
            trending: true,
            image: require('../static/products/airmax-01.jpg'),
            imageHover: require('../static/products/airmax-02.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
        {
            id: 16,
            name: 'Cachecol',
            price: 191.00,
            offer: false,
            offerPrice: 4,
            latest: false,
            bestSellers: false,
            trending: true,
            image: require('../static/products/airmax-01.jpg'),
            imageHover: require('../static/products/airmax-02.jpg'),
            timePeriod: false,
            dateTime: new Date("December 19, 2020 17:00:00 PDT")
        },
    ]
});

export default {
    state
};