--DROP TABLE USUARIO; 
--DROP TABLE CATEGORIA; 
--DROP TABLE CLASSIFICACAO_ITEM; 
--DROP TABLE PRODUTO; 
--DROP TABLE PEDIDO; 
--DROP TABLE ANEXO_IMAGEM; 
--DROP TABLE MARCA; 
--DROP TABLE PRODUTO_OPCAO; 
--DROP TABLE OPCAO; 
--DROP TABLE LOGRADOURO; 
--DROP TABLE PRODUTO_CATEGORIA; 
--DROP TABLE SUBCATEGORIA; 
--DROP TABLE CATEGORIA_SUBCATEGORIA; 
--DROP TABLE SUBCATEGORIA_CLASSIFICACAO; 
--DROP TABLE PEDIDO_PRODUTO; 
--DROP TABLE TAGS; 
--DROP TABLE TAGS_PRODUTO; 
create table "USUARIO" ( 
	"ID_USUARIO" INTEGER NOT NULL, 
	"NOME_USUARIO" VARCHAR(255) NOT NULL, 
	"DATA_VALIDADE" DATETIME NOT NULL, 
	"SENHA_USUARIO" VARCHAR(255) NOT NULL, 
	"EMAIL" VARCHAR(60) NOT NULL, 
	"STATUS_USUARIO" ---- Undefined sql type: Generic ---- NOT NULL, 
	"TIPOPERMISSAO" ---- Undefined sql type: Generic ---- NOT NULL, 
	CONSTRAINT "PK_USUARIO" PRIMARY KEY ( id_usuario)); 
create table "CATEGORIA" ( 
	"ID_CATEGORIA" INTEGER NOT NULL, 
	"NOME" VARCHAR(255) NOT NULL, 
	"DATA_INCLUSAO" DATETIME NOT NULL, 
	"DATA_ALTERACAO" DATETIME NOT NULL, 
	"STATUSATIVIDADE" INTEGER NOT NULL, 
	CONSTRAINT "PK_CATEGORIA" PRIMARY KEY ( id_categoria)); 
create table "CLASSIFICACAO_ITEM" ( 
	"ID_CLASSIFICACAO" INTEGER NOT NULL, 
	"NOME" VARCHAR(255) NOT NULL, 
	"DATA_INCLUSAO" DATETIME NOT NULL, 
	"DATA_ALTERACAO" DATETIME NOT NULL, 
	"STATUSATIVIDADE" INTEGER NOT NULL, 
	CONSTRAINT "PK_CLASSIFICACAO_ITEM" PRIMARY KEY ( id_classificacao)); 
create table "PRODUTO" ( 
	"ID_PRODUTO" INTEGER NOT NULL, 
	"NOME" VARCHAR(255) NOT NULL, 
	"DESCRICAO" TEXT NOT NULL, 
	"DATA_INSERCAO" DATETIME NOT NULL, 
	"DATA_ATUALIZACAO" DATETIME NOT NULL, 
	"RATING" REAL(0,  2) NULL, 
	"STATUSATIVIDADE" INTEGER NOT NULL, 
	"ID_MARCA" INTEGER NOT NULL, 
	CONSTRAINT "PK_PRODUTO" PRIMARY KEY ( id_produto)); 
create table "PEDIDO" ( 
	"ID_PEDIDO" INTEGER NOT NULL, 
	"DATA_INCLUSAO" DATETIME NOT NULL, 
	"DATA_ALTERACAO" DATETIME NOT NULL, 
	"STATUSPEDIDO" ---- Undefined sql type: Generic ---- NOT NULL, 
	"ID_USUARIO" INTEGER NOT NULL, 
	CONSTRAINT "PK_PEDIDO" PRIMARY KEY ( id_pedido)); 
create table "ANEXO_IMAGEM" ( 
	"ID_ANEXO" INTEGER NOT NULL, 
	"DESCRICAO" TEXT NOT NULL, 
	"ID_PRODUTO" INTEGER NOT NULL, 
	CONSTRAINT "PK_ANEXO_IMAGEM" PRIMARY KEY ( id_anexo)); 
create table "MARCA" ( 
	"ID_MARCA" INTEGER NOT NULL, 
	"NOME" VARCHAR(255) NOT NULL, 
	"LOGO" TEXT NULL, 
	CONSTRAINT "PK_MARCA" PRIMARY KEY ( id_marca)); 
create table "PRODUTO_OPCAO" ( 
	"ID" INTEGER NOT NULL, 
	"NOME" VARCHAR(5) NOT NULL, 
	"COR" VARCHAR(20) NOT NULL, 
	"PRECO" REAL(0,  2) NOT NULL, 
	"QUANTIDADE" INTEGER NOT NULL, 
	"ID_PRODUTO" INTEGER NOT NULL, 
	"ID_OPCAO" INTEGER NOT NULL, 
	CONSTRAINT "PK_PRODUTO_OPCAO" PRIMARY KEY ( id)); 
create table "OPCAO" ( 
	"ID_OPCAO" INTEGER NOT NULL, 
	"NOME" VARCHAR(0) NOT NULL, 
	"STATUSATIVIDADE" INTEGER NOT NULL, 
	CONSTRAINT "PK_OPCAO" PRIMARY KEY ( id_opcao)); 
create table "LOGRADOURO" ( 
	"ID_LOGRADOURO" INTEGER NOT NULL, 
	"RUA" VARCHAR(0) NOT NULL, 
	"BAIRRO" VARCHAR(0) NOT NULL, 
	"NUMERO" VARCHAR(0) NOT NULL, 
	"CEP" VARCHAR(0) NOT NULL, 
	"CIDADE" VARCHAR(0) NOT NULL, 
	"ESTADO" VARCHAR(0) NOT NULL, 
	"COMPLEMENTO" VARCHAR(0) NOT NULL, 
	"UF" VARCHAR(2) NOT NULL, 
	"APELIDO" VARCHAR(0) NULL, 
	"ID_USUARIO" INTEGER NULL, 
	CONSTRAINT "PK_LOGRADOURO" PRIMARY KEY ( id_logradouro)); 
create table "PRODUTO_CATEGORIA" ( 
	"ID" INTEGER NOT NULL, 
	"ID_CATEGORIA" INTEGER NOT NULL, 
	"ID_PRODUTO" INTEGER NOT NULL, 
	CONSTRAINT "PK_PRODUTO_CATEGORIA" PRIMARY KEY ( id)); 
create table "SUBCATEGORIA" ( 
	"ID_SUBCATEGORIA" INTEGER NOT NULL, 
	"NOME" VARCHAR(255) NOT NULL, 
	"DATA_INCLUSAO" DATETIME NOT NULL, 
	"DATA_ALTERACAO" DATETIME NOT NULL, 
	"STATUSATIVIDADE" INTEGER NOT NULL, 
	CONSTRAINT "PK_SUBCATEGORIA" PRIMARY KEY ( id_subcategoria)); 
create table "CATEGORIA_SUBCATEGORIA" ( 
	"ID" INTEGER NOT NULL, 
	"ID_CATEGORIA" INTEGER NOT NULL, 
	"ID_SUBCATEGORIA" INTEGER NOT NULL, 
	CONSTRAINT "PK_CATEGORIA_SUBCATEGORIA" PRIMARY KEY ( id)); 
create table "SUBCATEGORIA_CLASSIFICACAO" ( 
	"ID" INTEGER NOT NULL, 
	"ID_CLASSIFICACAO" INTEGER NOT NULL, 
	"ID_SUBCATEGORIA" INTEGER NOT NULL, 
	CONSTRAINT "PK_SUBCATEGORIA_CLASSIFICACAO" PRIMARY KEY ( id)); 
create table "PEDIDO_PRODUTO" ( 
	"ID" INTEGER NOT NULL, 
	"ID_PRODUTO" INTEGER NOT NULL, 
	"ID_PEDIDO" INTEGER NOT NULL, 
	CONSTRAINT "PK_PEDIDO_PRODUTO" PRIMARY KEY ( id)); 
create table "TAGS" ( 
	"ID_TAG" INTEGER NOT NULL, 
	"NOME" VARCHAR(255) NOT NULL, 
	CONSTRAINT "PK_TAGS" PRIMARY KEY ( id_tag)); 
create table "TAGS_PRODUTO" ( 
	"ID_TAG_PRODUTO" INTEGER NOT NULL, 
	"ID_TAG" INTEGER NOT NULL, 
	"ID_PRODUTO" INTEGER NOT NULL, 
	CONSTRAINT "PK_TAGS_PRODUTO" PRIMARY KEY ( id_tag_produto)); 
create sequence "SEQ_USUARIO" start with 1 increment by 1; 
create sequence "SEQ_CATEGORIA" start with 1 increment by 1; 
create sequence "SEQ_CLASSIFICACAO_ITEM" start with 1 increment by 1; 
create sequence "SEQ_PRODUTO" start with 1 increment by 1; 
create sequence "SEQ_PEDIDO" start with 1 increment by 1; 
create sequence "SEQ_ANEXO_IMAGEM" start with 1 increment by 1; 
create sequence "SEQ_MARCA" start with 1 increment by 1; 
create sequence "SEQ_PRODUTO_OPCAO" start with 1 increment by 1; 
create sequence "SEQ_OPCAO" start with 1 increment by 1; 
create sequence "SEQ_LOGRADOURO" start with 1 increment by 1; 
create sequence "SEQ_PRODUTO_CATEGORIA" start with 1 increment by 1; 
create sequence "SEQ_SUBCATEGORIA" start with 1 increment by 1; 
create sequence "SEQ_CATEGORIA_SUBCATEGORIA" start with 1 increment by 1; 
create sequence "SEQ_SUBCATEGORIA_CLASSIFICACAO" start with 1 increment by 1; 
create sequence "SEQ_PEDIDO_PRODUTO" start with 1 increment by 1; 
create sequence "SEQ_TAGS" start with 1 increment by 1; 
create sequence "SEQ_TAGS_PRODUTO" start with 1 increment by 1; 
ALTER TABLE "PRODUTO" ADD CONSTRAINT "FK_PRODUTO_MARCA" FOREIGN KEY ("ID_MARCA") REFERENCES "MARCA" ("ID_MARCA");
CREATE INDEX IPRODUTO_MARCA ON "PRODUTO" ("ID_MARCA");

ALTER TABLE "PEDIDO" ADD CONSTRAINT "FK_PEDIDO_USUARIO" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO" ("ID_USUARIO");
CREATE INDEX IPEDIDO_USUARIO ON "PEDIDO" ("ID_USUARIO");

ALTER TABLE "ANEXO_IMAGEM" ADD CONSTRAINT "FK_ANEXO_IMAGEM_PRODUTO" FOREIGN KEY ("ID_PRODUTO") REFERENCES "PRODUTO" ("ID_PRODUTO");
CREATE INDEX IANEXO_IMAGEM_PRODUTO ON "ANEXO_IMAGEM" ("ID_PRODUTO");

ALTER TABLE "PRODUTO_OPCAO" ADD CONSTRAINT "FK_PRODUTO_OPCAO_PRODUTO" FOREIGN KEY ("ID_PRODUTO") REFERENCES "PRODUTO" ("ID_PRODUTO");
CREATE INDEX IPRODUTO_OPCAO_PRODUTO ON "PRODUTO_OPCAO" ("ID_PRODUTO");

ALTER TABLE "PRODUTO_OPCAO" ADD CONSTRAINT "FK_PRODUTO_OPCAO_OPCAO" FOREIGN KEY ("ID_OPCAO") REFERENCES "OPCAO" ("ID_OPCAO");
CREATE INDEX IPRODUTO_OPCAO_OPCAO ON "PRODUTO_OPCAO" ("ID_OPCAO");

ALTER TABLE "LOGRADOURO" ADD CONSTRAINT "FK_LOGRADOURO_USUARIO" FOREIGN KEY ("ID_USUARIO") REFERENCES "USUARIO" ("ID_USUARIO");
CREATE INDEX ILOGRADOURO_USUARIO ON "LOGRADOURO" ("ID_USUARIO");

ALTER TABLE "PRODUTO_CATEGORIA" ADD CONSTRAINT "FK_PRODUTO_CATEGORIA_CATEGORIA" FOREIGN KEY ("ID_CATEGORIA") REFERENCES "CATEGORIA" ("ID_CATEGORIA");
CREATE INDEX IPRODUTO_CATEGORIA_CATEGORIA ON "PRODUTO_CATEGORIA" ("ID_CATEGORIA");

ALTER TABLE "PRODUTO_CATEGORIA" ADD CONSTRAINT "FK_PRODUTO_CATEGORIA_PRODUTO" FOREIGN KEY ("ID_PRODUTO") REFERENCES "PRODUTO" ("ID_PRODUTO");
CREATE INDEX IPRODUTO_CATEGORIA_PRODUTO ON "PRODUTO_CATEGORIA" ("ID_PRODUTO");

ALTER TABLE "CATEGORIA_SUBCATEGORIA" ADD CONSTRAINT "FK_CATEGORIA_SUBCATEGORIA_CATEGORIA" FOREIGN KEY ("ID_CATEGORIA") REFERENCES "CATEGORIA" ("ID_CATEGORIA");
CREATE INDEX ICATEGORIA_SUBCATEGORIA_CATEGORIA ON "CATEGORIA_SUBCATEGORIA" ("ID_CATEGORIA");

ALTER TABLE "CATEGORIA_SUBCATEGORIA" ADD CONSTRAINT "FK_CATEGORIA_SUBCATEGORIA_SUBCATEGORIA" FOREIGN KEY ("ID_SUBCATEGORIA") REFERENCES "SUBCATEGORIA" ("ID_SUBCATEGORIA");
CREATE INDEX ICATEGORIA_SUBCATEGORIA_SUBCATEGORIA ON "CATEGORIA_SUBCATEGORIA" ("ID_SUBCATEGORIA");

ALTER TABLE "SUBCATEGORIA_CLASSIFICACAO" ADD CONSTRAINT "FK_SUBCATEGORIA_CLASSIFICACAO_CLASSIFICACAOITEM" FOREIGN KEY ("ID_CLASSIFICACAO") REFERENCES "CLASSIFICACAO_ITEM" ("ID_CLASSIFICACAO");
CREATE INDEX ISUBCATEGORIA_CLASSIFICACAO_CLASSIFICACAOITEM ON "SUBCATEGORIA_CLASSIFICACAO" ("ID_CLASSIFICACAO");

ALTER TABLE "SUBCATEGORIA_CLASSIFICACAO" ADD CONSTRAINT "FK_SUBCATEGORIA_CLASSIFICACAO_SUBCATEGORIA" FOREIGN KEY ("ID_SUBCATEGORIA") REFERENCES "SUBCATEGORIA" ("ID_SUBCATEGORIA");
CREATE INDEX ISUBCATEGORIA_CLASSIFICACAO_SUBCATEGORIA ON "SUBCATEGORIA_CLASSIFICACAO" ("ID_SUBCATEGORIA");

ALTER TABLE "PEDIDO_PRODUTO" ADD CONSTRAINT "FK_PEDIDO_PRODUTO_PRODUTO" FOREIGN KEY ("ID_PRODUTO") REFERENCES "PRODUTO" ("ID_PRODUTO");
CREATE INDEX IPEDIDO_PRODUTO_PRODUTO ON "PEDIDO_PRODUTO" ("ID_PRODUTO");

ALTER TABLE "PEDIDO_PRODUTO" ADD CONSTRAINT "FK_PEDIDO_PRODUTO_PEDIDO" FOREIGN KEY ("ID_PEDIDO") REFERENCES "PEDIDO" ("ID_PEDIDO");
CREATE INDEX IPEDIDO_PRODUTO_PEDIDO ON "PEDIDO_PRODUTO" ("ID_PEDIDO");

ALTER TABLE "TAGS_PRODUTO" ADD CONSTRAINT "FK_TAGS_PRODUTO_PRODUTO" FOREIGN KEY ("ID_PRODUTO") REFERENCES "PRODUTO" ("ID_PRODUTO");
CREATE INDEX ITAGS_PRODUTO_PRODUTO ON "TAGS_PRODUTO" ("ID_PRODUTO");

ALTER TABLE "TAGS_PRODUTO" ADD CONSTRAINT "FK_TAGS_PRODUTO_TAGS" FOREIGN KEY ("ID_TAG") REFERENCES "TAGS" ("ID_TAG");
CREATE INDEX ITAGS_PRODUTO_TAGS ON "TAGS_PRODUTO" ("ID_TAG");


--<#keep(end)#><#/keep(end)#>