


	DROP TABLE [dbo].[USUARIO]
	DROP TABLE [dbo].[CATEGORIA]
	DROP TABLE [dbo].[CLASSIFICACAO_ITEM]
	DROP TABLE [dbo].[PRODUTO]
	DROP TABLE [dbo].[PEDIDO]
	DROP TABLE [dbo].[ANEXO_IMAGEM]
	DROP TABLE [dbo].[MARCA]
	DROP TABLE [dbo].[PRODUTO_OPCAO]
	DROP TABLE [dbo].[OPCAO]
	DROP TABLE [dbo].[LOGRADOURO]
	DROP TABLE [dbo].[PRODUTO_CATEGORIA]
	DROP TABLE [dbo].[SUBCATEGORIA]
	DROP TABLE [dbo].[CATEGORIA_SUBCATEGORIA]
	DROP TABLE [dbo].[SUBCATEGORIA_CLASSIFICACAO]
	DROP TABLE [dbo].[PEDIDO_PRODUTO]
	DROP TABLE [dbo].[TAGS]
	DROP TABLE [dbo].[TAGS_PRODUTO]
GO


	create table [dbo].[USUARIO] (
		id_usuario BIGINT NOT NULL IDENTITY(1,1), 
		nome_usuario VARCHAR(255) NOT NULL, 
		data_validade DATETIME NOT NULL, 
		senha_usuario VARCHAR(255) NOT NULL, 
		email VARCHAR(60) NOT NULL, 
		status_usuario ----Undefinedsqltype:Generic---- NOT NULL, 
		TIPOPERMISSAO ----Undefinedsqltype:Generic---- NOT NULL, 
		CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED (
			id_usuario ASC) ON [PRIMARY]
	)

	create table [dbo].[CATEGORIA] (
		id_categoria INT NOT NULL IDENTITY(1,1), 
		nome VARCHAR(255) NOT NULL, 
		data_inclusao DATETIME NOT NULL, 
		data_alteracao DATETIME NOT NULL, 
		STATUSATIVIDADE INT NOT NULL, 
		CONSTRAINT [PK_CATEGORIA] PRIMARY KEY CLUSTERED (
			id_categoria ASC) ON [PRIMARY]
	)

	create table [dbo].[CLASSIFICACAO_ITEM] (
		id_classificacao INT NOT NULL IDENTITY(1,1), 
		nome VARCHAR(255) NOT NULL, 
		data_inclusao DATETIME NOT NULL, 
		data_alteracao DATETIME NOT NULL, 
		STATUSATIVIDADE INT NOT NULL, 
		CONSTRAINT [PK_CLASSIFICACAO_ITEM] PRIMARY KEY CLUSTERED (
			id_classificacao ASC) ON [PRIMARY]
	)

	create table [dbo].[PRODUTO] (
		id_produto BIGINT NOT NULL IDENTITY(1,1), 
		nome VARCHAR(255) NOT NULL, 
		descricao ----Undefinedsqltype:Text---- NOT NULL, 
		data_insercao DATETIME NOT NULL, 
		data_atualizacao DATETIME NOT NULL, 
		rating NUMERIC(0, 2) NULL, 
		STATUSATIVIDADE INT NOT NULL, 
		id_marca BIGINT NOT NULL, 
		CONSTRAINT [PK_PRODUTO] PRIMARY KEY CLUSTERED (
			id_produto ASC) ON [PRIMARY]
	)

	create table [dbo].[PEDIDO] (
		id_pedido BIGINT NOT NULL IDENTITY(1,1), 
		data_inclusao DATETIME NOT NULL, 
		data_alteracao DATETIME NOT NULL, 
		STATUSPEDIDO ----Undefinedsqltype:Generic---- NOT NULL, 
		id_usuario BIGINT NOT NULL, 
		CONSTRAINT [PK_PEDIDO] PRIMARY KEY CLUSTERED (
			id_pedido ASC) ON [PRIMARY]
	)

	create table [dbo].[ANEXO_IMAGEM] (
		id_anexo INT NOT NULL IDENTITY(1,1), 
		descricao ----Undefinedsqltype:Text---- NOT NULL, 
		id_produto BIGINT NOT NULL, 
		CONSTRAINT [PK_ANEXO_IMAGEM] PRIMARY KEY CLUSTERED (
			id_anexo ASC) ON [PRIMARY]
	)

	create table [dbo].[MARCA] (
		id_marca BIGINT NOT NULL IDENTITY(1,1), 
		nome VARCHAR(255) NOT NULL, 
		logo ----Undefinedsqltype:Text---- NULL, 
		CONSTRAINT [PK_MARCA] PRIMARY KEY CLUSTERED (
			id_marca ASC) ON [PRIMARY]
	)

	create table [dbo].[PRODUTO_OPCAO] (
		id BIGINT NOT NULL IDENTITY(1,1), 
		nome VARCHAR(5) NOT NULL, 
		cor VARCHAR(20) NOT NULL, 
		preco NUMERIC(0, 2) NOT NULL, 
		quantidade INT NOT NULL, 
		id_produto BIGINT NOT NULL, 
		id_opcao BIGINT NOT NULL, 
		CONSTRAINT [PK_PRODUTO_OPCAO] PRIMARY KEY CLUSTERED (
			id ASC) ON [PRIMARY]
	)

	create table [dbo].[OPCAO] (
		id_opcao BIGINT NOT NULL IDENTITY(1,1), 
		nome VARCHAR(0) NOT NULL, 
		STATUSATIVIDADE INT NOT NULL, 
		CONSTRAINT [PK_OPCAO] PRIMARY KEY CLUSTERED (
			id_opcao ASC) ON [PRIMARY]
	)

	create table [dbo].[LOGRADOURO] (
		id_logradouro INT NOT NULL IDENTITY(1,1), 
		rua VARCHAR(0) NOT NULL, 
		bairro VARCHAR(0) NOT NULL, 
		numero VARCHAR(0) NOT NULL, 
		cep VARCHAR(0) NOT NULL, 
		cidade VARCHAR(0) NOT NULL, 
		estado VARCHAR(0) NOT NULL, 
		complemento VARCHAR(0) NOT NULL, 
		uf VARCHAR(2) NOT NULL, 
		apelido VARCHAR(0) NULL, 
		id_usuario BIGINT NULL, 
		CONSTRAINT [PK_LOGRADOURO] PRIMARY KEY CLUSTERED (
			id_logradouro ASC) ON [PRIMARY]
	)

	create table [dbo].[PRODUTO_CATEGORIA] (
		id BIGINT NOT NULL IDENTITY(1,1), 
		id_categoria INT NOT NULL, 
		id_produto BIGINT NOT NULL, 
		CONSTRAINT [PK_PRODUTO_CATEGORIA] PRIMARY KEY CLUSTERED (
			id ASC) ON [PRIMARY]
	)

	create table [dbo].[SUBCATEGORIA] (
		id_subcategoria INT NOT NULL IDENTITY(1,1), 
		nome VARCHAR(255) NOT NULL, 
		data_inclusao DATETIME NOT NULL, 
		data_alteracao DATETIME NOT NULL, 
		STATUSATIVIDADE INT NOT NULL, 
		CONSTRAINT [PK_SUBCATEGORIA] PRIMARY KEY CLUSTERED (
			id_subcategoria ASC) ON [PRIMARY]
	)

	create table [dbo].[CATEGORIA_SUBCATEGORIA] (
		id BIGINT NOT NULL IDENTITY(1,1), 
		id_categoria INT NOT NULL, 
		id_subcategoria INT NOT NULL, 
		CONSTRAINT [PK_CATEGORIA_SUBCATEGORIA] PRIMARY KEY CLUSTERED (
			id ASC) ON [PRIMARY]
	)

	create table [dbo].[SUBCATEGORIA_CLASSIFICACAO] (
		id BIGINT NOT NULL IDENTITY(1,1), 
		id_classificacao INT NOT NULL, 
		id_subcategoria INT NOT NULL, 
		CONSTRAINT [PK_SUBCATEGORIA_CLASSIFICACAO] PRIMARY KEY CLUSTERED (
			id ASC) ON [PRIMARY]
	)

	create table [dbo].[PEDIDO_PRODUTO] (
		id BIGINT NOT NULL IDENTITY(1,1), 
		id_produto BIGINT NOT NULL, 
		id_pedido BIGINT NOT NULL, 
		CONSTRAINT [PK_PEDIDO_PRODUTO] PRIMARY KEY CLUSTERED (
			id ASC) ON [PRIMARY]
	)

	create table [dbo].[TAGS] (
		id_tag BIGINT NOT NULL IDENTITY(1,1), 
		nome VARCHAR(255) NOT NULL, 
		CONSTRAINT [PK_TAGS] PRIMARY KEY CLUSTERED (
			id_tag ASC) ON [PRIMARY]
	)

	create table [dbo].[TAGS_PRODUTO] (
		id_tag_produto BIGINT NOT NULL IDENTITY(1,1), 
		id_tag BIGINT NOT NULL, 
		id_produto BIGINT NOT NULL, 
		CONSTRAINT [PK_TAGS_PRODUTO] PRIMARY KEY CLUSTERED (
			id_tag_produto ASC) ON [PRIMARY]
	)

GO

ALTER TABLE [dbo].[PRODUTO] ADD CONSTRAINT [FK_PRODUTO_MARCA] FOREIGN KEY ([id_marca]) REFERENCES[dbo].[MARCA]([id_marca])
CREATE INDEX IPRODUTO_MARCA ON [PRODUTO] ([id_marca])
ALTER TABLE [dbo].[PEDIDO] ADD CONSTRAINT [FK_PEDIDO_USUARIO] FOREIGN KEY ([id_usuario]) REFERENCES[dbo].[USUARIO]([id_usuario])
CREATE INDEX IPEDIDO_USUARIO ON [PEDIDO] ([id_usuario])
ALTER TABLE [dbo].[ANEXO_IMAGEM] ADD CONSTRAINT [FK_ANEXO_IMAGEM_PRODUTO] FOREIGN KEY ([id_produto]) REFERENCES[dbo].[PRODUTO]([id_produto])
CREATE INDEX IANEXO_IMAGEM_PRODUTO ON [ANEXO_IMAGEM] ([id_produto])
ALTER TABLE [dbo].[PRODUTO_OPCAO] ADD CONSTRAINT [FK_PRODUTO_OPCAO_PRODUTO] FOREIGN KEY ([id_produto]) REFERENCES[dbo].[PRODUTO]([id_produto])
CREATE INDEX IPRODUTO_OPCAO_PRODUTO ON [PRODUTO_OPCAO] ([id_produto])
ALTER TABLE [dbo].[PRODUTO_OPCAO] ADD CONSTRAINT [FK_PRODUTO_OPCAO_OPCAO] FOREIGN KEY ([id_opcao]) REFERENCES[dbo].[OPCAO]([id_opcao])
CREATE INDEX IPRODUTO_OPCAO_OPCAO ON [PRODUTO_OPCAO] ([id_opcao])
ALTER TABLE [dbo].[LOGRADOURO] ADD CONSTRAINT [FK_LOGRADOURO_USUARIO] FOREIGN KEY ([id_usuario]) REFERENCES[dbo].[USUARIO]([id_usuario])
CREATE INDEX ILOGRADOURO_USUARIO ON [LOGRADOURO] ([id_usuario])
ALTER TABLE [dbo].[PRODUTO_CATEGORIA] ADD CONSTRAINT [FK_PRODUTO_CATEGORIA_CATEGORIA] FOREIGN KEY ([id_categoria]) REFERENCES[dbo].[CATEGORIA]([id_categoria])
CREATE INDEX IPRODUTO_CATEGORIA_CATEGORIA ON [PRODUTO_CATEGORIA] ([id_categoria])
ALTER TABLE [dbo].[PRODUTO_CATEGORIA] ADD CONSTRAINT [FK_PRODUTO_CATEGORIA_PRODUTO] FOREIGN KEY ([id_produto]) REFERENCES[dbo].[PRODUTO]([id_produto])
CREATE INDEX IPRODUTO_CATEGORIA_PRODUTO ON [PRODUTO_CATEGORIA] ([id_produto])
ALTER TABLE [dbo].[CATEGORIA_SUBCATEGORIA] ADD CONSTRAINT [FK_CATEGORIA_SUBCATEGORIA_CATEGORIA] FOREIGN KEY ([id_categoria]) REFERENCES[dbo].[CATEGORIA]([id_categoria])
CREATE INDEX ICATEGORIA_SUBCATEGORIA_CATEGORIA ON [CATEGORIA_SUBCATEGORIA] ([id_categoria])
ALTER TABLE [dbo].[CATEGORIA_SUBCATEGORIA] ADD CONSTRAINT [FK_CATEGORIA_SUBCATEGORIA_SUBCATEGORIA] FOREIGN KEY ([id_subcategoria]) REFERENCES[dbo].[SUBCATEGORIA]([id_subcategoria])
CREATE INDEX ICATEGORIA_SUBCATEGORIA_SUBCATEGORIA ON [CATEGORIA_SUBCATEGORIA] ([id_subcategoria])
ALTER TABLE [dbo].[SUBCATEGORIA_CLASSIFICACAO] ADD CONSTRAINT [FK_SUBCATEGORIA_CLASSIFICACAO_CLASSIFICACAOITEM] FOREIGN KEY ([id_classificacao]) REFERENCES[dbo].[CLASSIFICACAO_ITEM]([id_classificacao])
CREATE INDEX ISUBCATEGORIA_CLASSIFICACAO_CLASSIFICACAOITEM ON [SUBCATEGORIA_CLASSIFICACAO] ([id_classificacao])
ALTER TABLE [dbo].[SUBCATEGORIA_CLASSIFICACAO] ADD CONSTRAINT [FK_SUBCATEGORIA_CLASSIFICACAO_SUBCATEGORIA] FOREIGN KEY ([id_subcategoria]) REFERENCES[dbo].[SUBCATEGORIA]([id_subcategoria])
CREATE INDEX ISUBCATEGORIA_CLASSIFICACAO_SUBCATEGORIA ON [SUBCATEGORIA_CLASSIFICACAO] ([id_subcategoria])
ALTER TABLE [dbo].[PEDIDO_PRODUTO] ADD CONSTRAINT [FK_PEDIDO_PRODUTO_PRODUTO] FOREIGN KEY ([id_produto]) REFERENCES[dbo].[PRODUTO]([id_produto])
CREATE INDEX IPEDIDO_PRODUTO_PRODUTO ON [PEDIDO_PRODUTO] ([id_produto])
ALTER TABLE [dbo].[PEDIDO_PRODUTO] ADD CONSTRAINT [FK_PEDIDO_PRODUTO_PEDIDO] FOREIGN KEY ([id_pedido]) REFERENCES[dbo].[PEDIDO]([id_pedido])
CREATE INDEX IPEDIDO_PRODUTO_PEDIDO ON [PEDIDO_PRODUTO] ([id_pedido])
ALTER TABLE [dbo].[TAGS_PRODUTO] ADD CONSTRAINT [FK_TAGS_PRODUTO_PRODUTO] FOREIGN KEY ([id_produto]) REFERENCES[dbo].[PRODUTO]([id_produto])
CREATE INDEX ITAGS_PRODUTO_PRODUTO ON [TAGS_PRODUTO] ([id_produto])
ALTER TABLE [dbo].[TAGS_PRODUTO] ADD CONSTRAINT [FK_TAGS_PRODUTO_TAGS] FOREIGN KEY ([id_tag]) REFERENCES[dbo].[TAGS]([id_tag])
CREATE INDEX ITAGS_PRODUTO_TAGS ON [TAGS_PRODUTO] ([id_tag])

--<#keep(end)#><#/keep(end)#>